# Created with komac v2.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: nomic.gpt4all
PackageVersion: 2.7.1
PackageLocale: en-US
Publisher: Nomic
PublisherUrl: https://www.nomic.ai/
PackageName: GPT4All
PackageUrl: https://github.com/nomic-ai/gpt4all
License: MIT
LicenseUrl: https://github.com/nomic-ai/gpt4all/blob/main/LICENSE.txt
Copyright: Copyright (c) 2023 Nomic, Inc.
ShortDescription: GPT4All is a GUI application for loading and interacting with Generative AI models
Tags:
- llm-inference
ReleaseNotesUrl: https://github.com/nomic-ai/gpt4all/releases/tag/v2.7.1
ManifestType: defaultLocale
ManifestVersion: 1.6.0
